### ISSUE TITLE
DMG envelop change without retriggering sounds wrong

### ISSUE THREAD

**Issue by copyrat90** [nba-emu/NanoBoyAdvance#335] opened 2023-11-15 06:00 UTC
In the hardware, the envelop goes as expected, but in NBA it stops the sound immediately.

## Hardware -> NBA recording

https://github.com/nba-emu/NanoBoyAdvance/assets/34793045/7341a28e-f89e-4710-9dc1-1a639bf18e74

## Test ROM
[F0_F7_no_retrig.zip](https://github.com/nba-emu/NanoBoyAdvance/files/13360768/F0_F7_no_retrig.zip)

## Code

```c
#include <tonc.h>

int main(void) {
    irq_init(NULL);
    irq_enable(II_VBLANK);

    REG_SNDSTAT = SSTAT_ENABLE;
    REG_SNDDSCNT = SDS_DMG100;
    REG_SNDDMGCNT = SDMG_LVOL(7) | SDMG_RVOL(7) | SDMG_LSQR1 | SDMG_RSQR1;

    REG_SND1CNT = SSQR_IVOL(15) | SSQR_TIME(0);
    REG_SND1FREQ = SFREQ_RESET | SFREQ_RATE(416);

    int wait = 45;
    while (1) {
        if (--wait == 0)
            REG_SND1CNT = SSQR_IVOL(15) | SSQR_TIME(7);
        VBlankIntrWait();
    }
}
```

**Comment by copyrat90** [comment] 2023-11-15 06:53
Setting the sound length while playing is also behaves differently.

## Hardware -> NBA recording

https://github.com/nba-emu/NanoBoyAdvance/assets/34793045/9fa9469a-d166-4e0e-b12d-73e16a7039c4

## Test ROM

[length_repeat.zip](https://github.com/nba-emu/NanoBoyAdvance/files/13361196/length_repeat.zip)

## Code

```c
#include <tonc.h>

int main(void) {
    irq_init(NULL);
    irq_enable(II_VBLANK);

    REG_SNDSTAT = SSTAT_ENABLE;
    REG_SNDDSCNT = SDS_DMG100;
    REG_SNDDMGCNT = SDMG_LVOL(7) | SDMG_RVOL(7) | SDMG_LSQR1 | SDMG_RSQR1;

    REG_SND1CNT = SSQR_IVOL(15) | SSQR_TIME(7) | SSQR_LEN(0);
    REG_SND1FREQ = SFREQ_RESET | SFREQ_RATE(416) | SFREQ_TIMED;

    int wait = 5;
    while (1) {
        if (--wait == 0) {
            REG_SND1CNT = SSQR_IVOL(15) | SSQR_TIME(7) | SSQR_LEN(0);
            wait = 5;
        }
        VBlankIntrWait();
    }
}
```

**Comment by copyrat90** [comment] 2023-11-15 08:00
Also, setting the initial envelop volume while playing shouldn't cut the note away.

## Recordings

Hardware

https://github.com/nba-emu/NanoBoyAdvance/assets/34793045/48a8b338-8a3b-40dc-a3ae-2b7496a6b753

NBA

https://github.com/nba-emu/NanoBoyAdvance/assets/34793045/57ba6505-0cf8-4934-9844-934ec3267b08

## Test ROM

[volume_set_midplay.zip](https://github.com/nba-emu/NanoBoyAdvance/files/13361839/volume_set_midplay.zip)

## Code

```c
#include <tonc.h>

int main(void) {
    irq_init(NULL);
    irq_enable(II_VBLANK);

    REG_SNDSTAT = SSTAT_ENABLE;
    REG_SNDDSCNT = SDS_DMG100;
    REG_SNDDMGCNT = SDMG_LVOL(7) | SDMG_RVOL(7) | SDMG_LSQR1 | SDMG_RSQR1;

    REG_SND1CNT = SSQR_IVOL(15) | SSQR_TIME(0);
    REG_SND1FREQ = SFREQ_RESET | SFREQ_RATE(416);

    int wait = 45;
    while (1) {
        if (--wait == 0) {
            REG_SND1CNT = SSQR_IVOL(7) | SSQR_TIME(0);
        }
        VBlankIntrWait();
    }
}
```

**Comment by fleroviux** [comment] 2023-11-15 19:51
Thanks for all these tests. I will take a look at this asap!

**Comment by fleroviux** [comment] 2023-11-15 21:43
All three tests should be with commit https://github.com/nba-emu/NanoBoyAdvance/commit/ba587e4ee063226ab6712746fc100273ff65103a. Most of these issues were caused by implementing the bugged envelope "Zombie" mode described to exist in GB sound documentation. However it turns out that the "Zombie" mode may have been fixed on GBA systems.

This change can be tested with the latest [development build](https://nightly.link/nba-emu/NanoBoyAdvance/workflows/build/master).

**Closed by fleroviux** 2023-11-15 21:43 UTC
Labels: accuracy, hw: apu
