### ISSUE TITLE
SNES controller does not work correctly

### ISSUE THREAD

**Issue by 1985a** [nba-emu/NanoBoyAdvance#254] opened 2022-08-14 19:59 UTC
NanoBoyAdvance: Git version 3bb6f47
My OS: Archlinux kernel 5.18.15
Original SNES Controller.
SNES USB adapter: [see here](https://www.amazon.com/SNES-Controller-Adapter-USB-Super-NES/dp/B002IXZ5DE)
I've been using it since 2009. It works nice yet. It detects by the system as HuiJia USB GamePad
The system has installed SDL2 as well.

I was trying to configure the AXIS, but it does not work well. Only work down and right AXIS.
If I press quickly down, it then shows that I'm pressing up when that is not the case.
[see a video here](https://streamable.com/slsvbt)

[some-imgs](https://imgur.com/a/NaR7r4H)

Finally, here a dump from the conf file.

> recent_files = [
"/roms/GBA/Metroid - Fusion.gba",
"/roms/GBA/Final Fight One (U).gba",
]
[general]
bios_path = "/gba_bios.bin"
bios_skip = false
[input]
fast_forward = [
32,
2,
4,
]
hold_fast_forward = true
controller_guid = "030000008f0e00001330000010010000"
[input.gba]
b = [
83,
3,
-1,
]
a = [
0,
1,
-1,
]
select = [
16777219,
4,
-1,
]
right = [
16777236,
14,
1,
]
r = [
70,
10,
-1,
]
l = [
68,
9,
-1,
]
left = [
16777234,
14,
-1,
]
start = [
16777220,
6,
-1,
]
down = [
16777237,
12,
1,
]
up = [
16777235,
12,
-1,
]

**Comment by fleroviux** [comment] 2023-07-31 13:06
I have merged an overhaul of the controller emulation earlier, which might fix this issue.
Can you download the latest [development build](https://nightly.link/nba-emu/NanoBoyAdvance/workflows/build/master) and check if the issue is fixed, please?

Thanks.

**Comment by fleroviux** [comment] 2023-11-15 21:51
Closing because a very similar issue with a different controller had been fixed by the aforementioned overhaul. Like the other issue this issue likely also is an issue with the button mapping provided by the SDL GameController API. However we switched from the SDL GameController API to the SDL JoyStick API, which means that the user has to manually map their controller anyway.

**Closed by fleroviux** 2023-11-15 21:51 UTC
Labels: frontend: Qt
